apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-egress-demo-workload

resources:
  - namespace.yaml
  - curller.yaml
  
components:
  - git@github.com:openshift-examples/kustomize/components/simple-http-server

patches:
- patch: |-
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: simple-http-server
    spec:
      host: simple-http-server.alpha.coe.muc.redhat.com
      tls:
        insecureEdgeTerminationPolicy: Allow